#ifndef __SAT_SDK_LIB_CONFIG_H__
#define __SAT_SDK_LIB_CONFIG_H__

// c
#include <cstdlib>
#include <ctime>
#include <cstring>

// c++
#include <iostream>
#include <iomanip>
#include <fstream>
#include <string>
#include <sstream>
#include <vector>
#include <map>
#include <queue>
#include <deque>
#include <list>
#include <utility>
#include <algorithm>

// pthread
#include <pthread.h>

// module enable config (automatically generated by cmake)
#include "sat_sdk_lib_module_config.h"

// platform specific config
#include "sat_sdk_lib_platform.h"

// debug functions
#include "sat_sdk_lib_debug.h"

// api return code definition
#include "sat_sdk_lib_return_code.h"

// enum
#include "sat_sdk_lib_enum.h"

// structure
#include "sat_sdk_lib_structure.h"

// pjlib
#include "pj/config_site.h"
#include <pjlib.h>
#include <pjlib-util.h>
#include <pjnath.h>

// for _stat
#include <sys/types.h>
#include <sys/stat.h>

// a function to release all p2p resource, can be called before process exit
// if not called, just let the system to do garbage collection
void sat_sdk_lib_release();

#endif /* __SAT_SDK_LIB_CONFIG_H__ */
